### ISSUE TITLE
single-shot "shutdown when finished" option

### ISSUE THREAD

**Issue by HuBandiT** [lordmulder/Simple-x264-Launcher#11]
I would like to have the option of requesting Launcher to shut down the computer after the last job in the queue completed, but only just for the current session.

Often when I come back to work on video the next day after having enabled this option for overnight encoding jobs, I forget I have this option enabled. So when I start a job that I want to check the result of, and step away from the computer to work elsewhere (so I an not there to cancel the shutdown in the appearing dialog), Launcher shuts down my computer without me actually intending it to.

This is where an option "shut down when everything finished - but just this once" would be useful.

**Comment by lordmulder** [comment]
I will consider adding an option for this. But I do **not** consider this a top priority at the moment.

**Comment by lordmulder** [comment]
Took a while, but here is a new TEST build:
[**x264_launcher-TEST.2018-02-26.exe**](https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2018-02-26.exe/download)
