### ISSUE TITLE
Chinese simplfied translation text and picture uploaded

### ISSUE THREAD

**Issue by iAvoe** [lordmulder/Simple-x264-Launcher#12]
I don't know how to work in the code but I've made a series of pictures and text files so you should be able to just copy and paste into the code, if the texts in the file are all jammed together rename .txt to .doc should fix, thanks for providing this gui by the way :)

[x264 Launcher translation Chinese Simplfied.zip](https://github.com/lordmulder/Simple-x264-Launcher/files/1958340/x264.Launcher.translation.Chinese.Simplfied.zip)

**Comment by lordmulder** [comment]
Hello,

thank you. Unfortunately, I cannot use it like this. Please have a look at the translator's guide:
[**Translate.html**](http://lamexp.osdn.io/doc/Translate.html)
