### ISSUE TITLE
disabling x265 version check

### ISSUE THREAD

**Issue by 0zymandia2** [lordmulder/Simple-x264-Launcher#14]
Hi,

I use Yuuki's mod for anime, and it hasn't been updated in quite some time. I can't currently use it anymore because of the version check.

I read in the doom9 forum, your post saying that "you must decrease the minimum required x264 [x265] version manually", how do you achieve that?

**Comment by lordmulder** [comment]
Hello,

please see [README](https://github.com/lordmulder/Simple-x264-Launcher#command-line-syntax) on how to skip version check. Use at your own risk 😏 

Regards,
MuldeR
