### ISSUE TITLE
Program malfunction

### ISSUE THREAD

**Issue by Vpstr** [lordmulder/Simple-x264-Launcher#15]
I just downloaded the program and at once found that having created a job once I can't view its parameters later, because the "Explore job" menu item is inactive (tried 2 different formats). If I can't view the settings of a particular job, the program is practically useless.

**Comment by lordmulder** [comment]
Hello.

You cannot edit parameters, once the job has been started. But you can see them in the log!

For example:

```
Simple x264 Launcher (Build #1138), built 2018-10-12

Job started at 2018-10-22, 20:37:42.

Source file : E:\ViDeOz\Samples\Netflix_RitualDance_4096x2160_60fps_10bit_420.y4m
Output file : C:\Users\MuldeR\Videos\Netflix_RitualDance_4096x2160_60fps_10bit_420.hevc

--- SYSTEMINFO ---

Binary Path : C:\Program Files (x86)\MuldeR\Simple x264 Launcher v2
Avisynth    : Yes
VapourSynth : Yes

--- SETTINGS ---

Encoder : x265 (HEVC/H.265), 64-Bit (x64), 10-Bit
Source  : Native
RC Mode : CRF
Preset  : fast
Tuning  : <None>
Profile : <Unrestricted>
Custom  : <None>
```
The menu item "Explore job" is to show the generated output file, *once the job has finished*. You can also use "Restart Job", which will effectively clone the existing job and allow you to edit parameters.

Regards,
MuldeR
