### ISSUE TITLE
mkv output for x265 files

### ISSUE THREAD

**Issue by HyerrDoktyer** [lordmulder/Simple-x264-Launcher#17]
Greetings,

Currently when attempting to output an x265 to an .mkv container you are met with this error warning:

![111](https://user-images.githubusercontent.com/34185288/58896563-5e806500-8735-11e9-9462-4beb22602083.png)

As far as I'm aware, x265 can output .mkv files, unless I'm mistaken? I apologize if this is indeed a limitation of x265.

**Comment by lordmulder** [comment]
Nope, x265.exe (x265 CLI encoder) does **not** support MKV output; only "raw" H.265 (HEVC) streams.

FFmpeg, for example, supports encoding via libx265 (x265 encoder library) and it can output MKV files, using its own MKV muxer.
