### ISSUE TITLE
Expandable "Custom encoder paramaters"

### ISSUE THREAD

**Issue by HyerrDoktyer** [lordmulder/Simple-x264-Launcher#18]
When dealing with a long string of custom options, it can be quite annoying dealing with the single line options box that this launcher provides. Would it be possible to have an expandable box, to allow for easier editing of parameters? For example, here on github you can expand and contract the comment box at will.
Currently I hop between a .txt file when I need to edit anything.

**Comment by lordmulder** [comment]
Right click in the edit box and choose "Open Text-Editor" from the context menu 😄

**Comment by HyerrDoktyer** [comment]
Thank you!

**Comment by lordmulder** [comment]
You are welcome.
