### ISSUE TITLE
Vapoursynth path not detected

### ISSUE THREAD

**Issue by Intervencion** [lordmulder/Simple-x264-Launcher#20]
I've Vapoursynth R47 installed on the default path (APPDATA\Local\Programs\Vapoursynth) and using latest Simple x264 Launcher build (v2.9.1180) but I'm being given this warning when I try to use a VPY and on the console it says the text from under here

Windows 10 btw

```
[Check for VapourSynth support]
VapourSynth thread has been created, please wait...
VapourSynth install path not found -> disable VapouSynth support!
VapourSynth thread finished.
VapourSynth could not be found -> VapourSynth support disabled!
```

**Comment by lordmulder** [comment]
Hello.

Default install path should be `C:\Program Files\VapourSynth` for the 64-Bit version of VapourSynth, and  `C:\Program Files (x86)\VapourSynth-32` for the 32-Bit version – on the 64-Bit OS.

Anyway, Simple x264 Launcher does **not** assume any hardcoded install path, but instead reads the actual install path from the registry. This is the proper way of "detecting" VapourSynth.

If VapourSynth was properly installed, these registry entries should exist:
- **64-Bit Windows**
  - 64-Bit version: `HKEY_LOCAL_MACHINE\SOFTWARE\VapourSynth\Path`
  - 32-Bit version: `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VapourSynth\Path`
- **32-Bit Windows**
  - 32-Bit version: `HKEY_LOCAL_MACHINE\SOFTWARE\VapourSynth\Path`

It would seem that these registry keys have not been found. Can you verify they exist?

Regards
MuldeR

**Comment by Intervencion** [comment]
I'm using 64-bit Window but neither of the registry entries exist.

**Comment by lordmulder** [comment]
> I'm using 64-bit Window but neither of the registry entries exist.

So, yeah, that explains why VapourSynth could **not** be detect 😏 

It does not explain, though, why the registry keys appear to be missing on your system. Was VapourSynth installed using the official installer (**`VapourSynth64-R47.exe`**) or did you just unzip the "portable" package? You ***have*** to use the installer! For instructions on how to use the "protable" package with Simple x264 Launcher, please see the instructions in my README file.

**Comment by Intervencion** [comment]
I installed with the R47 installer, not portable. I'll reinstall again and see... I'll LYK

**Comment by lordmulder** [comment]
I have tested VapourSynth detection on 32-Bit and 64-Bit Windows. On 64-Bit the detection of 32-Bit and 64-Bit version have been tested. Always worked for me on Windows 10 and Windows 8.1.

**Comment by lordmulder** [comment]
BTW: When installing VapourSynth its is **very** important to select *"Install for all users (recommended)", because only this will create a "system-wide" installation of VapourSynth that other applications can detect.

**Comment by Intervencion** [comment]
Yep. 

So I installed Py3.7 with "install for all users preset" but it seems it's bugged? Because it kept installing to current only (even if launching as admin).

Had to go to advanced installation and select manually All Users. 

Obviously now Vapoursynth has installed properly and Simple X264 Launcher detects the installation.

Thanks for the help!

**Comment by lordmulder** [comment]
I have added a workaround to detect VapourSynth even when installed only for the current user:
[**x264_launcher-TEST.2019-08-12.exe**](https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2019-08-12.exe/download)

Regards.

**Comment by lordmulder** [comment]
I have added a workaround to detect VapourSynth even when installed only for the current user:
[**x264_launcher-TEST.2019-08-13.exe**](https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2019-08-13.exe/download)

Regards.
