### ISSUE TITLE
Waiting Jobs Are Lost in Case of Unclean Exit

### ISSUE THREAD

**Issue by gashtal** [lordmulder/Simple-x264-Launcher#21]
If there are pending/waiting jobs in Simple x264/x265 Launcher and the application is exited cleanly, these jobs will still be available when the application is launched again. However, if the application is not closed cleanly, e.g. in the case of a power cut or OS crash, then all running and pending jobs will be lost and the next time the application is started, the job window will be empty. Is it possible for the behavior of the application to be improved in such cases?

**Comment by lordmulder** [comment]
Pending jobs are saved when the application terminates "normally".

In the very rare case of a power cut or OS crash your pending jobs are lost, yes. But I have **no** plans to do anything about that at the moment. If you encounter power cut or OS crash regularly, then you have a much bigger problem elsewhere...
