### ISSUE TITLE
Please add a option to disable the sound when shutdown computer on completion

### ISSUE THREAD

**Issue by ted423** [lordmulder/Simple-x264-Launcher#25]
I had unchecked this 
![image](https://user-images.githubusercontent.com/7042766/93501143-a1287980-f947-11ea-8a47-788327fb1900.png),
but I think this is not about that.
And when I fall sleep,the jop finished.............It's awake me up

**Comment by lordmulder** [comment]
Well, the sound is there to warn people that their computer will shut down soon and all unsaved data is lost.

Last chance to save your unsaved work, you know.

Therefore, I'm not sure it is a good idea to disable that sound effect. Maybe just turn your speakers off before go to sleep? 😸 

Regards.

**Comment by ted423** [comment]
> Well, the sound is there to warn people that their computer will shut down soon and all unsaved data is lost.
> 
> Last chance to abort the shutdown and save your unsaved work, you know.
> 
> Therefore, I'm not sure it is a good idea to disable that sound effect. Maybe just turn your speakers off before go to sleep? 😸
> 
> Regards.

Most of the time I will, but sometimes I forget.
Would it be better to get a countdown confirmation window?
