### ISSUE TITLE
Stop exiting on hibernation

### ISSUE THREAD

**Issue by Komic** [lordmulder/Simple-x264-Launcher#27]
Losing completed jobs is incredibly annoying, even more when the "Recently Used" template doesn't actually reflect what were the settings of my last jobs. Please just hibernate, and let me exit or not on resume.

**Comment by lordmulder** [comment]
You mean, application should not exit at all, when "Hibernate Computer" is set as "On Completion" action?

I will consider implementing this for next release.

Regards.

**Comment by Komic** [comment]
Yes. Thank you!

**Comment by lordmulder** [comment]
Implemented in 7fe6779177716755fd4ff282dc2f58024882bb0b.
