### ISSUE TITLE
Disable 6-month Update Notification

### ISSUE THREAD

**Issue by gashtal** [lordmulder/Simple-x264-Launcher#30]
Considering the development pace of this application, it has happened a few times that no new versions were released in 6 month, and the built-in forced update notification displayed in such circumstances at application launch, which cannot be discarded until after multiple seconds of waiting, turns from a useful reminder, into an annoyance. An option to permanently disable or discard this notification would be quite helpful.

**Comment by JFizDaWiz** [comment]
agree, it's quite the annoyance now

**Comment by lordmulder** [comment]
New version is out now:
https://github.com/lordmulder/Simple-x264-Launcher/releases/tag/v3.01
