### ISSUE TITLE
Update Notification is Back

### ISSUE THREAD

**Issue by gashtal** [lordmulder/Simple-x264-Launcher#32]
We just hit the anniversary of the last update of the application, and the update notification is back again. Any chance of getting an option to disable the notification for good this time? Previous issue for reference: #30

**Comment by lordmulder** [comment]
Sorry, new version will be released soon.

**Comment by lordmulder** [comment]
Try this:
https://mega.nz/file/kW0UwaTZ#yyTCR7RQg2hFDTOHTzE44h0ylJNCzOMFW7qfWqTOM2s
https://mega.nz/file/cblxmaLC#Bu5Erg7lxXoOmh9sCnaqNrlYbqrPexFATtsLbXKVHko

**Comment by lordmulder** [comment]
New version is up now!
