### ISSUE TITLE
vs r68 protable issue vapoursynth.dll  miss 

### ISSUE THREAD

**Issue by ted423** [lordmulder/Simple-x264-Launcher#35]
https://github.com/lordmulder/Simple-x264-Launcher/issues/31
use this file

vapoursynth.dll miss in R68
```
[Check for VapourSynth support]
VapourSynth thread has been created, please wait...
VapourSynth 32-Bit support is being tested.
VapourSynth 32-Bit edition *not* found!
VapourSynth 64-Bit support is being tested.
VapourSynth EXE: Z:/x264_launcher_avx/extra/VapourSynth-64/vspipe.exe
VapourSynth DLL: Z:/x264_launcher_avx/extra/VapourSynth-64/vapoursynth.dll
VapourSynth 64-Bit edition was found, but appears to be incomplete!
VapourSynth thread finished.
VapourSynth could not be found -> VapourSynth support disabled!
```

**Comment by ted423** [comment]
63/64/65 has this file
66/67/68 remove this dll

**Comment by ted423** [comment]
![image](https://github.com/lordmulder/Simple-x264-Launcher/assets/7042766/5d2692b2-2525-414f-ba82-b651b7e5464b)
this vs can work with command line

**Comment by ted423** [comment]
```
iirc starting with R66 there is no VapourSynth.dll in the main folder, there is only one in the Lib/site-packages-folder
```
https://forum.selur.net/thread-3720.html

I move this file out ,and pre-release version worked 
![image](https://github.com/lordmulder/Simple-x264-Launcher/assets/7042766/05910fd7-8d7b-4be9-9d01-5ddfea09fda0)

but I think that file don't need put it in that position anymore.

**Comment by lordmulder** [comment]
Just did a _clean_ re-install of Python 3.12.4 and VapourSynth R69.

VapourSynth was detected properly by latest release version:
```
[Check for VapourSynth support]
VapourSynth thread has been created, please wait...
VapourSynth 32-Bit support is being tested.
VapourSynth 32-Bit edition *not* found!
VapourSynth 64-Bit support is being tested.
VapourSynth EXE: C:/Program Files/VapourSynth/core/vspipe.exe
VapourSynth DLL: C:/Program Files/VapourSynth/core/vapoursynth.dll
VapourSynth version was detected successfully.
VapourSynth 64-Bit edition found!
VapourSynth thread finished.
VapourSynth support is officially enabled now! [x86=0, x64=1]
```

**Comment by ted423** [comment]
Simple-x264-Launcher python and vsr68 is protable and fresh setup by Install-Portable-VapourSynth-R68.ps1

and I found r69 protable still not include VapourSynth.dll with his protable https://github.com/vapoursynth/vapoursynth/releases/download/R69/VapourSynth64-Portable-R69.zip

**Comment by ted423** [comment]
> I just did a _**clean**_ re-install of Python 3.12.4 and VapourSynth R69.
> 
> VapourSynth was detected properly by latest release version of Simple x264/x265 Launcher:
> 
> ```
> Simple x264 Launcher v3.04.1225 - use 64-Bit x264 with 32-Bit Avisynth
> Copyright (c) 2004-2024 LoRd_MuldeR <mulder2@gmx.de>. Some rights reserved.
> Built on 2024-07-14 at 16:39:25 with MSVC 2022.10 for Win-x86.
> 
> ...
> 
> [Check for VapourSynth support]
> VapourSynth thread has been created, please wait...
> VapourSynth 32-Bit support is being tested.
> VapourSynth 32-Bit edition *not* found!
> VapourSynth 64-Bit support is being tested.
> VapourSynth EXE: C:/Program Files/VapourSynth/core/vspipe.exe
> VapourSynth DLL: C:/Program Files/VapourSynth/core/vapoursynth.dll
> VapourSynth version was detected successfully.
> VapourSynth 64-Bit edition found!
> VapourSynth thread finished.
> VapourSynth support is officially enabled now! [x86=0, x64=1]
> ```
> 
> In particular, the file `C:/Program Files/VapourSynth/core/vapoursynth.dll` _does_ exist with a "fresh" install of VapourSynth R69 **and** it was detected correctly by Simple x264/x265 Launcher. So I suppose that the problem is fixed with VS R69.
> 
> If file `vapoursynth.dll` missing on your system, please try re-install of VapourSynth R69.

![image](https://github.com/user-attachments/assets/a1ccec60-f26a-48c6-881c-871b163f3d47)

**Comment by ted423** [comment]
after powershell run

![image](https://github.com/user-attachments/assets/31203d9a-d8c9-4c43-ab58-34952211f244)


I didn't make it clear, it's in portable mode, the VapourSynth.dll path move to Lib\site-packages

**Comment by ted423** [comment]
in ps1
```
if ($Python38) {
    Move-Item -Path "$TargetFolder\VSScriptPython38.dll" -Destination "$TargetFolder\VSScript.dll" -Force
} else {
    Remove-Item -Path "$TargetFolder\VSScriptPython38.dll"
}
Write-Host "Installing VapourSynth..."
& "$TargetFolder\python.exe" "-m" "pip" "install" "$TargetFolder\wheel\VapourSynth-$VSVersion-cp$PythonVersionMajor$PythonVersionMid-cp$PythonVersionMajor$PythonVersionMid-win_amd64.whl"

Write-Host "Installation complete" -ForegroundColor Green
```

**Comment by ted423** [comment]
vapoursynth.dll is in the VapourSynth-69-cp312-cp312-win_amd64.whl

**Comment by ted423** [comment]
seems the newest version worked

**Comment by ted423** [comment]
Currently, x264_launcher will not prompt directly, but it will prompt no VS when begin encode.
you can use a 0byte file named vapoursynth.dll in old path to bypass the vs check in x264_launcher
![image](https://github.com/user-attachments/assets/ac137685-e6d6-49bf-998b-68b925af7861)

**Comment by lordmulder** [comment]
Not quite sure if I understand everything you wrote, but I just did some changes to VapourSynth detection that should also fix the detection of the "portable" version. It seems that we should have been checking for `VSScript.dll` after all...

Please try new version here:
[x264_launcher-TEST.2024-07-21.exe](https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2024-07-21.exe/download)

**Comment by ted423** [comment]
> Not quite sure if I understand everything you wrote, but I just did some changes to VapourSynth detection that should also fix the detection of the "portable" version. It seems that we should have been checking for `VSScript.dll` after all...
> 
> Please try new version here: [x264_launcher-TEST.2024-07-21.exe](https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2024-07-21.exe/download)

![image](https://github.com/user-attachments/assets/ace4fe17-2ada-4e94-a12a-67af5e35166d)
worked

**Comment by lordmulder** [comment]
Okay, nice!
