### ISSUE TITLE
OpenCL encode errors

### ISSUE THREAD

**Issue by Anduin1357** [lordmulder/Simple-x264-Launcher#5]
Simple x264 Launcher (Build #902), built 2015-01-31

Job started at 2015-02-27, 21:11:21.

Source file : 
Output file : 

--- SYSTEMINFO ---

Binary Path : F:\Program Files (Bit-32_64)\x264vfwGUI
Avisynth    : Yes
VapourSynth : N/A

--- SETTINGS ---

Encoder : x264 (H.264/AVC), x64, 8-Bit
Source  : Native
RC Mode : CRF
Preset  : Slower
Tuning  : <None>
Profile : <Unrestricted>
Custom  : --opencl

--- CHECK VERSION ---

Detect video encoder version:

Creating process:
"F:\Program Files (Bit-32_64)\x264vfwGUI\toolset\x64\x264_8bit_x64.exe" --version

x264 0.144.2525 40bb568
(libswscale 3.1.101)
(libavformat 56.16.101)
(ffmpegsource 2.17.4.0)
built by Komisar on Dec 21 2014, gcc: 4.9.2 (multilib.generic.Komisar)
configuration: --bit-depth=8 --chroma-format=all
x264 license: GPL version 2 or later
libswscale/libavformat/ffmpegsource license: GPL version 2 or later

> x264 revision: 2525 (core #144)

--- ENCODING VIDEO ---

Creating encoder process:
"F:\Program Files (Bit-32_64)\x264vfwGUI\toolset\x64\x264_8bit_x64.exe" --crf 22.0 --preset slower --opencl --output "###" --index C:\~adb88ecc3375c3b08a83.ffindex "F:\~\robloxplayerbeta-02272015-000150.avi"

ffms [info]: 1368x768p 1:1 @ 30028/1001 fps (vfr)
x264 [info]: using SAR=1/1
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x264 [info]: OpenCL acceleration enabled with Intel(R) Corporation Intel(R) HD Graphics 4000
x264 [info]: profile High, level 4.2
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: x264_encoder_encode failed
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
x264 [error]: OpenCL: Unknown error
x264 [error]: OpenCL: fatal error, aborting encode
aborted at input frame 67, output frame 0

PROCESS EXITED WITH ERROR CODE: -1

//
Latest Intel driver as of 2015-02-27

**Comment by lordmulder** [comment]
Hello.

First of all, this obviously is **not** a *GUI* issue, so this is the wrong place. If you need support for *x264*, use the [x264 mailing list](http://www.videolan.org/developers/lists.html), the [IRC channel](irc://irc.freenode.net/x264) or the [forum](https://forum.doom9.org/forumdisplay.php?f=77).

Anyway, has OpenCL support in x264 ever been working with *Intel* GPU's? As far as I remember, Intel drivers have been notoriously broken with regard to OpenCL. Don't know if the situation has ever been improved. Furthermore, Intel GPU's are pretty weak, so getting OpenCL support to work is probably pointless to begin with...
