### ISSUE TITLE
Suport for Nvidia Nvenc

### ISSUE THREAD

**Issue by hyperion1is** [lordmulder/Simple-x264-Launcher#6]
Hi, 
I'm using your program. Is simple and intuitive.
I have a request. Can you add support for Nvidia Nvenc https://en.wikipedia.org/wiki/Nvidia_NVENC  ?
I have tried with DvdFab and Staxrip and I had a dramatic increase in encoding speed on my Nvidia Gtx 960. From 6h to 20 minutes. But those apps have their drawbacks. 
Can you add this feature for Simple-x264-Launcher?
Thanks!

**Comment by lordmulder** [comment]
First of all, x264 (with default settings) is known to produce **much** better quality than NVENC or QuickSync. So if you compare the speed of x264 (with default settings) to NVENC, then you are comparing apples and oranges! However, while NVENC can **not** be configured to produce better quality, x264 **can** be configured to encode much faster. So please try x264 with a **faster** *preset*!

As for adding support to for NVENC to Simple-x264-Launcher: You need to understand that NVENC is **not** a program like `x264.exe` or `x265.exe` that you can simply launch and that's it. Instead, NVENC is a dedicated piece of *hardware* that is "built-in" with your (NVidia) graphics card. So somebody needs to write an encoder application that makes use of the NVENC hardware for encoding. If there was a simple **command-line** program for encoding video with NVENC, which provides a similar interface to  `x264.exe` and `x265.exe`, it *might* be added to  Simple-x264-Launcher. But I'm *not* aware of such program. Not that I have looked for it...

**Comment by hyperion1is** [comment]
A command-line program exists. I don't know about the interface: NVEncC by rigaya. You  can try to Google it or see this topic if it helps: http://forum.videohelp.com/threads/370223-NVEncC-by-rigaya-NVIDIA-GPU-encoding.
In the mean time I also found out about the quality difference between the two. Still, if it is worth implementing is up to you.
Have a good day!

**Comment by lordmulder** [comment]
Okay, I will have a look at NVEncC, when I have time.
