### ISSUE TITLE
disable timeout on job startup

### ISSUE THREAD

**Issue by HuBandiT** [lordmulder/Simple-x264-Launcher#7]
Simple-x264-Launcher times my job out when I try to encode a VapourSynth script that is backed by a 465 GB (half terabyte) uncompressed video file that takes roughly an hour to index.

I would like to have an option for Simple-x264-Launcher not to time out on jobs at all; or, if you prefer, to be able to specify a longer timeout (either globally, or per-job).

**Comment by lordmulder** [comment]
Hi. There currently is no GUI option for that, but you can use the
`--no-deadlock-detection` option, as described in the README file. Note
that this is an option for the Simple x264 *main* program. It will *not*
work as an "custom parameter" in the Add Job dialog.

Regards,
MuldeR

**Comment by HuBandiT** [comment]
Ahh, great, thanks. In that case consider https://github.com/HuBandiT/Simple-x264-Launcher/pull/1
