### ISSUE TITLE
AviSynth script creator and support for subtitles ass

### ISSUE THREAD

**Issue by MakuSensei** [lordmulder/Simple-x264-Launcher#9]
Hello wanted to ask if you could add some support for creating AviSynth script as has MeGUI to record the ASS subtitles mp4

**Comment by lordmulder** [comment]
I have **no** plans for that at the moment.

**Comment by HuBandiT** [comment]
@MakuSensei you might want to check out [StaxRip](https://github.com/stax76/staxrip/) for a MeGUI-like high-level tool that supports VapourSynth.
